name: t21_seis

channels:
  - conda-forge
  - pyviz
  - defaults
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - xarray
  - segyio
  - scipy
  - panel
  - hvplot
  - dask
  - jupyter
  - pip
  - pip:
    - seismic-zfp
